begin;

create table if not exists public.suporte_tickets (
  id text primary key,
  modulo text not null check (modulo in ('DLT', 'DLH')),
  assunto text not null,
  categoria text,
  prioridade text,
  mensagem text not null,
  pagina text,
  status text not null default 'aberto',
  usuario_id uuid,
  usuario_email text,
  usuario_nome text,
  criado_em timestamptz not null default now()
);

create table if not exists public.suporte_ticket_mensagens (
  id bigint generated by default as identity primary key,
  ticket_id text not null references public.suporte_tickets(id) on delete cascade,
  autor_tipo text not null check (autor_tipo in ('usuario', 'suporte', 'sistema')),
  autor_nome text,
  autor_email text,
  mensagem text not null,
  canal text not null default 'sistema',
  telegram_update_id text unique,
  criado_em timestamptz not null default now()
);

create index if not exists suporte_ticket_mensagens_ticket_criado_idx
  on public.suporte_ticket_mensagens (ticket_id, criado_em);

alter table public.suporte_tickets enable row level security;
alter table public.suporte_ticket_mensagens enable row level security;

drop policy if exists "usuarios leem os proprios tickets" on public.suporte_tickets;
create policy "usuarios leem os proprios tickets"
on public.suporte_tickets
for select
to authenticated
using (usuario_id = auth.uid());

drop policy if exists "usuarios leem mensagens dos proprios tickets" on public.suporte_ticket_mensagens;
create policy "usuarios leem mensagens dos proprios tickets"
on public.suporte_ticket_mensagens
for select
to authenticated
using (
  exists (
    select 1
    from public.suporte_tickets ticket
    where ticket.id = suporte_ticket_mensagens.ticket_id
      and ticket.usuario_id = auth.uid()
  )
);

revoke all on public.suporte_tickets from anon;
revoke all on public.suporte_ticket_mensagens from anon;
grant select on public.suporte_tickets to authenticated;
grant select on public.suporte_ticket_mensagens to authenticated;

commit;
